export const products = [
  {
    id: 'linen-trench',
    name: 'Linen Utility Trench',
    category: 'Outerwear',
    price: 128,
    rating: 4.8,
    stock: 12,
    featuredScore: 96,
    image: 'https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=900&q=80',
    description: 'A breathable longline trench with soft structure, deep pockets, and an easy drape.',
  },
  {
    id: 'daily-sneaker',
    name: 'Cloudstep Daily Sneaker',
    category: 'Footwear',
    price: 92,
    rating: 4.7,
    stock: 18,
    featuredScore: 91,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    description: 'Cushioned leather sneakers made for city miles and clean enough for dinner after.',
  },
  {
    id: 'studio-tote',
    name: 'Studio Carryall Tote',
    category: 'Bags',
    price: 74,
    rating: 4.9,
    stock: 9,
    featuredScore: 89,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80',
    description: 'A structured tote with laptop storage, zipped essentials pocket, and recycled lining.',
  },
  {
    id: 'ribbed-set',
    name: 'Ribbed Lounge Set',
    category: 'Apparel',
    price: 86,
    rating: 4.6,
    stock: 16,
    featuredScore: 84,
    image: 'https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?auto=format&fit=crop&w=900&q=80',
    description: 'Soft ribbed separates with a relaxed fit that still looks pulled together.',
  },
  {
    id: 'ceramic-watch',
    name: 'Ceramic Field Watch',
    category: 'Accessories',
    price: 155,
    rating: 4.8,
    stock: 7,
    featuredScore: 94,
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80',
    description: 'A slim ceramic case, scratch-resistant crystal, and a comfortable woven strap.',
  },
  {
    id: 'weekend-duffel',
    name: 'Weekender Duffel',
    category: 'Bags',
    price: 118,
    rating: 4.5,
    stock: 10,
    featuredScore: 87,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',
    description: 'Cabin-friendly duffel with a shoe garage, reinforced handles, and water-resistant finish.',
  },
  {
    id: 'wool-overshirt',
    name: 'Brushed Wool Overshirt',
    category: 'Apparel',
    price: 112,
    rating: 4.7,
    stock: 14,
    featuredScore: 88,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',
    description: 'Warm enough as a jacket, easy enough as a shirt, finished with horn-style buttons.',
  },
  {
    id: 'runner-sandal',
    name: 'Trail Runner Sandal',
    category: 'Footwear',
    price: 68,
    rating: 4.4,
    stock: 22,
    featuredScore: 80,
    image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80',
    description: 'Lightweight sandals with grippy soles, adjustable webbing, and quick-dry comfort.',
  },
];